# Instalación de phpMyAdmin
- name: Instalar phpMyAdmin y dependencias
  apt:
    pkg:
      - phpmyadmin
      - php-mysql
    state: present
    update_cache: yes

# Configuración para conectar a MariaDB remoto
- name: Configurar phpMyAdmin para MariaDB remoto
  template:
    src: remote-db.php.j2
    dest: /etc/phpmyadmin/conf.d/remote-db.php
    owner: root
    group: root
    mode: '0644'
  notify: Reiniciar Apache
