#SPDX-License-Identifier: MIT-0
---
# defaults file for phpmyadmin
# Variables por defecto
pma_user: "phpmyadmin"
pma_pass: "phpmyadmin"
pma_path: "''"
pma_db: "guestbook_db"
pma_server: "10.0.0.2"
pma_port: "3306"
pma_type: "mysql"
