- name: aplicar reglas
  shell: /root/reglas.sh

- name: systemd
  systemd:
    daemon_reload: yes

- name: forwarding
  systemd:
    name: forwarding
    state: restarted
    enabled: yes

- name: nat
  systemd:
    name: NATworking
    state: restarted
    enabled: yes
