- hosts: servidores_web
  become: true
  roles:
   - role: nat 

- hosts: all
  become: true
  roles:
   - role: commons

- hosts: servidores_web
  become: true
  roles:
   - role: apache2
   - role: phpmyadmin
   - role: docker-compose

- hosts: servidores_bd
  become: true
  roles:
   - role: mariadb

- hosts: servidores_app
  become: true
  roles:
    - role: phpfpm
